/** Auto-gerado por scripts/generate-construct-placements.mjs — NÃO editar.
 * Fonte: public/construct-world/data.json (NPCs).
 * Regenerar: npm run sync:construct | npm run prepare:construct | npm run generate:construct-placements
 */

import type { ConstructNpcInstancePlacement, ConstructNpcPlacement } from './constructNpcPlacements.js';

/** Todas as instâncias — multi-spawn (ex.: humano_1#0, humano_1#1). */
export const CONSTRUCT_NPC_INSTANCES_GENERATED: readonly ConstructNpcInstancePlacement[] = [
  { instanceId: 'alquimista', archetypeId: 'alquimista', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 108, constructY: 708 },
  { instanceId: 'anciao_cael', archetypeId: 'anciao_cael', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 479, constructY: 262 },
  { instanceId: 'ativador_boss#0', archetypeId: 'ativador_boss', mapId: 'tower_floor_1', constructLayout: 'andar_1_torre_poder', constructX: 323, constructY: 348 },
  { instanceId: 'ativador_boss#1', archetypeId: 'ativador_boss', mapId: 'tower_floor_2', constructLayout: 'andar_2_torre_poder', constructX: 320, constructY: 350 },
  { instanceId: 'ativador_boss#2', archetypeId: 'ativador_boss', mapId: 'tower_floor_3', constructLayout: 'andar_3_torre_poder', constructX: 322, constructY: 353 },
  { instanceId: 'ativador_boss#3', archetypeId: 'ativador_boss', mapId: 'tower_floor_4', constructLayout: 'andar_4_torre_poder2', constructX: 322, constructY: 345 },
  { instanceId: 'ativador_boss#4', archetypeId: 'ativador_boss', mapId: 'tower_floor_5', constructLayout: 'andar_5_torre_poder3', constructX: 322, constructY: 355 },
  { instanceId: 'banqueiro', archetypeId: 'banqueiro', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 959, constructY: 376 },
  { instanceId: 'cao_robo#0', archetypeId: 'cao_robo', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 663, constructY: 570 },
  { instanceId: 'cao_robo#1', archetypeId: 'cao_robo', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 521, constructY: 1224 },
  { instanceId: 'combate_pvp', archetypeId: 'combate_pvp', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 542, constructY: 714 },
  { instanceId: 'computador_arena', archetypeId: 'computador_arena', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 656, constructY: 789 },
  { instanceId: 'computador_marketplace', archetypeId: 'computador_marketplace', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 278, constructY: 574 },
  { instanceId: 'computador_towerpower', archetypeId: 'computador_towerpower', mapId: 'tower_gate', constructLayout: 'entradatorredopoder', constructX: 312, constructY: 679 },
  { instanceId: 'computador_zona1', archetypeId: 'computador_zona1', mapId: 'farm_zone_01', constructLayout: 'zonabeco1', constructX: 62, constructY: 1418 },
  { instanceId: 'computador_zona1a', archetypeId: 'computador_zona1a', mapId: 'farm_zone_01', constructLayout: 'zonabeco1a', constructX: 1101, constructY: 498 },
  { instanceId: 'contrabandista#0', archetypeId: 'contrabandista', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 1218, constructY: 369 },
  { instanceId: 'contrabandista#1', archetypeId: 'contrabandista', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 319, constructY: 1179 },
  { instanceId: 'enter_spaw_towerpower', archetypeId: 'enter_spaw_towerpower', mapId: 'tower_gate', constructLayout: 'entradatorredopoder', constructX: 714, constructY: 675 },
  { instanceId: 'ferreiro', archetypeId: 'ferreiro', mapId: 'tower_gate', constructLayout: 'entradatorredopoder', constructX: 1198, constructY: 614 },
  { instanceId: 'humano_1#0', archetypeId: 'humano_1', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 591, constructY: 154 },
  { instanceId: 'humano_1#1', archetypeId: 'humano_1', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 634, constructY: 614 },
  { instanceId: 'humano_1#2', archetypeId: 'humano_1', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 669, constructY: 718 },
  { instanceId: 'humano_1#3', archetypeId: 'humano_1', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 847, constructY: 867 },
  { instanceId: 'humano_1#4', archetypeId: 'humano_1', mapId: 'tower_gate', constructLayout: 'entradatorredopoder', constructX: 110, constructY: 650 },
  { instanceId: 'humano_1#5', archetypeId: 'humano_1', mapId: 'tower_gate', constructLayout: 'entradatorredopoder', constructX: 1046, constructY: 790 },
  { instanceId: 'humano_1#6', archetypeId: 'humano_1', mapId: 'farm_zone_01', constructLayout: 'zonabeco1', constructX: 387, constructY: 416 },
  { instanceId: 'humano_1#7', archetypeId: 'humano_1', mapId: 'farm_zone_01', constructLayout: 'zonabeco1', constructX: 228, constructY: 752 },
  { instanceId: 'humano_1#8', archetypeId: 'humano_1', mapId: 'farm_zone_01', constructLayout: 'zonabeco1', constructX: 188, constructY: 1205 },
  { instanceId: 'humano_1#9', archetypeId: 'humano_1', mapId: 'farm_zone_01', constructLayout: 'zonabeco1', constructX: 428, constructY: 1294 },
  { instanceId: 'humano_1#10', archetypeId: 'humano_1', mapId: 'farm_zone_01', constructLayout: 'zonabeco1a', constructX: 1360, constructY: 194 },
  { instanceId: 'humano_2#0', archetypeId: 'humano_2', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 616, constructY: 317 },
  { instanceId: 'humano_2#1', archetypeId: 'humano_2', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 439, constructY: 613 },
  { instanceId: 'humano_2#2', archetypeId: 'humano_2', mapId: 'tower_gate', constructLayout: 'entradatorredopoder', constructX: 1037, constructY: 98 },
  { instanceId: 'humano_2#3', archetypeId: 'humano_2', mapId: 'tower_gate', constructLayout: 'entradatorredopoder', constructX: 166, constructY: 112 },
  { instanceId: 'humano_2#4', archetypeId: 'humano_2', mapId: 'tower_gate', constructLayout: 'entradatorredopoder', constructX: 380, constructY: 183 },
  { instanceId: 'humano_2#5', archetypeId: 'humano_2', mapId: 'tower_gate', constructLayout: 'entradatorredopoder', constructX: 1209, constructY: 191 },
  { instanceId: 'humano_2#6', archetypeId: 'humano_2', mapId: 'tower_gate', constructLayout: 'entradatorredopoder', constructX: 58, constructY: 483 },
  { instanceId: 'humano_2#7', archetypeId: 'humano_2', mapId: 'tower_gate', constructLayout: 'entradatorredopoder', constructX: 822, constructY: 681 },
  { instanceId: 'humano_2#8', archetypeId: 'humano_2', mapId: 'farm_zone_01', constructLayout: 'zonabeco1', constructX: 426, constructY: 604 },
  { instanceId: 'humano_2#9', archetypeId: 'humano_2', mapId: 'farm_zone_01', constructLayout: 'zonabeco1', constructX: 242, constructY: 994 },
  { instanceId: 'humano_2#10', archetypeId: 'humano_2', mapId: 'farm_zone_01', constructLayout: 'zonabeco1', constructX: 575, constructY: 1478 },
  { instanceId: 'humano_2#11', archetypeId: 'humano_2', mapId: 'farm_zone_01', constructLayout: 'zonabeco1a', constructX: 1652, constructY: 337 },
  { instanceId: 'leave_level_power_tower2', archetypeId: 'leave_level_power_tower2', mapId: 'tower_floor_5', constructLayout: 'andar_5_torre_poder3', constructX: -2904, constructY: 2813 },
  { instanceId: 'membro_gang_rosa#0', archetypeId: 'membro_gang_rosa', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 862, constructY: 81 },
  { instanceId: 'membro_gang_rosa#1', archetypeId: 'membro_gang_rosa', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 944, constructY: 102 },
  { instanceId: 'membro_gang_rosa#2', archetypeId: 'membro_gang_rosa', mapId: 'farm_zone_01', constructLayout: 'zonabeco1a', constructX: 1635, constructY: 548 },
  { instanceId: 'membro_gang_rosa#3', archetypeId: 'membro_gang_rosa', mapId: 'farm_zone_01', constructLayout: 'zonabeco1a', constructX: 1533, constructY: 560 },
  { instanceId: 'membro_gang_rosa#4', archetypeId: 'membro_gang_rosa', mapId: 'farm_zone_01', constructLayout: 'zonabeco1a', constructX: 1569, constructY: 618 },
  { instanceId: 'mercador_rua', archetypeId: 'mercador_rua', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 229, constructY: 813 },
  { instanceId: 'mercenario', archetypeId: 'mercenario', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 1041, constructY: 454 },
  { instanceId: 'mestre_trilhas', archetypeId: 'mestre_trilhas', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 972, constructY: 1193 },
  { instanceId: 'next_level_power_tower#0', archetypeId: 'next_level_power_tower', mapId: 'tower_floor_1', constructLayout: 'andar_1_torre_poder', constructX: -6, constructY: 497 },
  { instanceId: 'next_level_power_tower#1', archetypeId: 'next_level_power_tower', mapId: 'tower_floor_2', constructLayout: 'andar_2_torre_poder', constructX: 6, constructY: 480 },
  { instanceId: 'next_level_power_tower#2', archetypeId: 'next_level_power_tower', mapId: 'tower_floor_3', constructLayout: 'andar_3_torre_poder', constructX: 6, constructY: 481 },
  { instanceId: 'next_level_power_tower#3', archetypeId: 'next_level_power_tower', mapId: 'tower_floor_4', constructLayout: 'andar_4_torre_poder2', constructX: -6, constructY: 493 },
  { instanceId: 'next_level_power_tower#4', archetypeId: 'next_level_power_tower', mapId: 'tower_floor_5', constructLayout: 'andar_5_torre_poder3', constructX: 30, constructY: 487 },
  { instanceId: 'operario_linha4#0', archetypeId: 'operario_linha4', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 371, constructY: 124 },
  { instanceId: 'operario_linha4#1', archetypeId: 'operario_linha4', mapId: 'farm_zone_01', constructLayout: 'zonabeco1a', constructX: 203, constructY: 111 },
  { instanceId: 'operario_linha4#2', archetypeId: 'operario_linha4', mapId: 'farm_zone_01', constructLayout: 'zonabeco1a', constructX: 1098, constructY: 126 },
  { instanceId: 'operario_linha4#3', archetypeId: 'operario_linha4', mapId: 'farm_zone_01', constructLayout: 'zonabeco1a', constructX: 2152, constructY: 127 },
  { instanceId: 'receptador#0', archetypeId: 'receptador', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 743, constructY: 193 },
  { instanceId: 'receptador#1', archetypeId: 'receptador', mapId: 'farm_zone_01', constructLayout: 'zonabeco1', constructX: 133, constructY: 1368 },
  { instanceId: 'receptador#2', archetypeId: 'receptador', mapId: 'farm_zone_01', constructLayout: 'zonabeco1a', constructX: 914, constructY: 599 },
  { instanceId: 'tecnico_manutencao', archetypeId: 'tecnico_manutencao', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 410, constructY: 539 },
  { instanceId: 'treinador_zeno', archetypeId: 'treinador_zeno', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 459, constructY: 1181 },
  { instanceId: 'vendedor', archetypeId: 'vendedor', mapId: 'city_01', constructLayout: 'cidade_01', constructX: 1157, constructY: 919 },
];

/** Primeira instância por archetype — compat gates / terminais. */
export const CONSTRUCT_NPC_PLACEMENTS_GENERATED: Readonly<
  Record<string, ConstructNpcPlacement>
> = {
  alquimista: { mapId: 'city_01', constructLayout: 'cidade_01', constructX: 108, constructY: 708 },
  anciao_cael: { mapId: 'city_01', constructLayout: 'cidade_01', constructX: 479, constructY: 262 },
  ativador_boss: { mapId: 'tower_floor_1', constructLayout: 'andar_1_torre_poder', constructX: 323, constructY: 348 },
  banqueiro: { mapId: 'city_01', constructLayout: 'cidade_01', constructX: 959, constructY: 376 },
  cao_robo: { mapId: 'city_01', constructLayout: 'cidade_01', constructX: 663, constructY: 570 },
  combate_pvp: { mapId: 'city_01', constructLayout: 'cidade_01', constructX: 542, constructY: 714 },
  computador_arena: { mapId: 'city_01', constructLayout: 'cidade_01', constructX: 656, constructY: 789 },
  computador_marketplace: { mapId: 'city_01', constructLayout: 'cidade_01', constructX: 278, constructY: 574 },
  computador_towerpower: { mapId: 'tower_gate', constructLayout: 'entradatorredopoder', constructX: 312, constructY: 679 },
  computador_zona1: { mapId: 'farm_zone_01', constructLayout: 'zonabeco1', constructX: 62, constructY: 1418 },
  computador_zona1a: { mapId: 'farm_zone_01', constructLayout: 'zonabeco1a', constructX: 1101, constructY: 498 },
  contrabandista: { mapId: 'city_01', constructLayout: 'cidade_01', constructX: 1218, constructY: 369 },
  enter_spaw_towerpower: { mapId: 'tower_gate', constructLayout: 'entradatorredopoder', constructX: 714, constructY: 675 },
  ferreiro: { mapId: 'tower_gate', constructLayout: 'entradatorredopoder', constructX: 1198, constructY: 614 },
  humano_1: { mapId: 'city_01', constructLayout: 'cidade_01', constructX: 591, constructY: 154 },
  humano_2: { mapId: 'city_01', constructLayout: 'cidade_01', constructX: 616, constructY: 317 },
  leave_level_power_tower2: { mapId: 'tower_floor_5', constructLayout: 'andar_5_torre_poder3', constructX: -2904, constructY: 2813 },
  membro_gang_rosa: { mapId: 'city_01', constructLayout: 'cidade_01', constructX: 862, constructY: 81 },
  mercador_rua: { mapId: 'city_01', constructLayout: 'cidade_01', constructX: 229, constructY: 813 },
  mercenario: { mapId: 'city_01', constructLayout: 'cidade_01', constructX: 1041, constructY: 454 },
  mestre_trilhas: { mapId: 'city_01', constructLayout: 'cidade_01', constructX: 972, constructY: 1193 },
  next_level_power_tower: { mapId: 'tower_floor_1', constructLayout: 'andar_1_torre_poder', constructX: -6, constructY: 497 },
  operario_linha4: { mapId: 'city_01', constructLayout: 'cidade_01', constructX: 371, constructY: 124 },
  receptador: { mapId: 'city_01', constructLayout: 'cidade_01', constructX: 743, constructY: 193 },
  tecnico_manutencao: { mapId: 'city_01', constructLayout: 'cidade_01', constructX: 410, constructY: 539 },
  treinador_zeno: { mapId: 'city_01', constructLayout: 'cidade_01', constructX: 459, constructY: 1181 },
  vendedor: { mapId: 'city_01', constructLayout: 'cidade_01', constructX: 1157, constructY: 919 },
};
