import type { SkillData } from '../types.js';
import {
  MoveEffectKind,
  MoveTarget,
  type MoveEffectKind as MoveEffectKindType,
  type MoveTarget as MoveTargetType,
} from './classMovesetCatalog.js';
import { MoveCategory, MoveScalingStat, type MoveDefinition } from './moveTypes.js';

type MonsterSkillDefinition = MoveDefinition & {
  readonly effectKind?: MoveEffectKindType;
  readonly effectParams?: Readonly<Record<string, number>>;
  readonly moveTarget?: MoveTargetType;
};

function skill(
  partial: MonsterSkillDefinition,
): MonsterSkillDefinition {
  return partial;
}

/**
 * Skills de criaturas — fora do moveset de classe do jogador.
 * Debuffs reusam MoveEffectKind / effectParams do CombatEngine (params Z1 mais fracos).
 */
export const MONSTER_SKILL_CATALOG: readonly MonsterSkillDefinition[] = [
  // ── Zone 1 — básicos (PureDamage) ─────────────────────────────────────
  skill({
    id: 'rat_bite',
    name: 'Mordida',
    category: MoveCategory.Attack,
    scalingStat: MoveScalingStat.STR,
    damage: 12,
    cooldown: 1,
    priority: 1,
    ppMax: 24,
    description: 'Ataque básico do rato.',
    effectKind: MoveEffectKind.PureDamage,
    moveTarget: MoveTarget.Enemy,
  }),
  skill({
    id: 'spider_bite',
    name: 'Mordida',
    category: MoveCategory.Attack,
    scalingStat: MoveScalingStat.STR,
    damage: 13,
    cooldown: 1,
    priority: 1,
    ppMax: 24,
    description: 'Ataque básico da aranha.',
    effectKind: MoveEffectKind.PureDamage,
    moveTarget: MoveTarget.Enemy,
  }),
  skill({
    id: 'bat_strike',
    name: 'Investida',
    category: MoveCategory.Attack,
    scalingStat: MoveScalingStat.AGI,
    damage: 11,
    cooldown: 1,
    priority: 1,
    ppMax: 24,
    description: 'Ataque básico do morcego.',
    effectKind: MoveEffectKind.PureDamage,
    moveTarget: MoveTarget.Enemy,
  }),
  skill({
    id: 'crow_slash',
    name: 'Gadanha',
    category: MoveCategory.Attack,
    scalingStat: MoveScalingStat.AGI,
    damage: 12,
    cooldown: 1,
    priority: 1,
    ppMax: 24,
    description: 'Ataque básico do corvo.',
    effectKind: MoveEffectKind.PureDamage,
    moveTarget: MoveTarget.Enemy,
  }),
  skill({
    id: 'wild_dog_snap',
    name: 'Estalo',
    category: MoveCategory.Attack,
    scalingStat: MoveScalingStat.STR,
    damage: 14,
    cooldown: 1,
    priority: 1,
    ppMax: 24,
    description: 'Ataque básico do cão selvagem.',
    effectKind: MoveEffectKind.PureDamage,
    moveTarget: MoveTarget.Enemy,
  }),

  // ── Zone 1 — debuffs (1 slot) ─────────────────────────────────────────
  skill({
    id: 'rat_septic',
    name: 'Mordida Séptica',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.STR,
    damage: 8,
    cooldown: 2,
    priority: 2,
    ppMax: 10,
    description: 'Mordida infecciosa — enfraquece o moveset do alvo.',
    effectKind: MoveEffectKind.MovesetWeaken,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      weakenPercent: 10,
      weakenTurns: 2,
      debuffUntilBattleEnd: 0,
      battleEndDebuffWeakenPercent: 0,
    },
  }),
  skill({
    id: 'spider_venom',
    name: 'Peçonha',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.CRIT,
    damage: 6,
    cooldown: 2,
    priority: 2,
    ppMax: 10,
    description: 'Veneno paralisante.',
    effectKind: MoveEffectKind.ApplyParalyze,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      paralyzeSkipTurnChance: 45,
      paralyzeTurns: 1,
      incomingBuffWeakenPercent: 10,
      incomingBuffWeakenTurns: 2,
    },
  }),
  skill({
    id: 'bat_screech',
    name: 'Guincho',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.CRIT,
    damage: 7,
    cooldown: 2,
    priority: 2,
    ppMax: 10,
    description: 'Ultrassom desorientador — confusão.',
    effectKind: MoveEffectKind.Confuse,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      confuseFailChance: 35,
      residualDamageFromEnemyAttackPercent: 6,
      residualTurns: 2,
    },
  }),
  skill({
    id: 'crow_peck',
    name: 'Bicada Debilitante',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.AGI,
    damage: 9,
    cooldown: 2,
    priority: 2,
    ppMax: 10,
    description: 'Bicada que enfraquece levemente o moveset.',
    effectKind: MoveEffectKind.MovesetWeaken,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      weakenPercent: 8,
      weakenTurns: 2,
      debuffUntilBattleEnd: 0,
      battleEndDebuffWeakenPercent: 0,
    },
  }),
  skill({
    id: 'wild_dog_bite',
    name: 'Mordida Sangrenta',
    category: MoveCategory.Attack,
    scalingStat: MoveScalingStat.STR,
    damage: 10,
    cooldown: 2,
    priority: 1,
    ppMax: 10,
    description: 'Ferida aberta modelada como Burn (DoT).',
    effectKind: MoveEffectKind.ApplyBurn,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      burnDamagePercent: 3,
      burnTurns: 2,
    },
  }),

  // ── Elite / Zone 2–3 (perfil + skills nomeadas; wired quando zona entra) ─
  skill({
    id: 'specter_wail',
    name: 'Lamento',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.CRIT,
    damage: 10,
    cooldown: 2,
    priority: 2,
    ppMax: 10,
    description: 'Lamento espectral — confusão.',
    effectKind: MoveEffectKind.Confuse,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      confuseFailChance: 40,
      residualDamageFromEnemyAttackPercent: 8,
      residualTurns: 2,
    },
  }),
  skill({
    id: 'specter_phase',
    name: 'Deslocamento',
    category: MoveCategory.Utility,
    scalingStat: MoveScalingStat.AGI,
    damage: 0,
    cooldown: 3,
    priority: 3,
    ppMax: 6,
    description: 'Fase espectral (comportamento especial).',
    effectKind: MoveEffectKind.PureDamage,
    moveTarget: MoveTarget.Self,
  }),
  skill({
    id: 'specter_chill',
    name: 'Frio do Véu',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.CRIT,
    damage: 8,
    cooldown: 2,
    priority: 2,
    ppMax: 10,
    description: 'Enfraquece o moveset.',
    effectKind: MoveEffectKind.MovesetWeaken,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      weakenPercent: 12,
      weakenTurns: 2,
      debuffUntilBattleEnd: 0,
      battleEndDebuffWeakenPercent: 0,
    },
  }),
  skill({
    id: 'minotaur_charge',
    name: 'Investida',
    category: MoveCategory.Attack,
    scalingStat: MoveScalingStat.STR,
    damage: 18,
    cooldown: 1,
    priority: 1,
    ppMax: 16,
    description: 'Carga do minotauro.',
    effectKind: MoveEffectKind.PureDamage,
    moveTarget: MoveTarget.Enemy,
  }),
  skill({
    id: 'minotaur_gore',
    name: 'Chifrada',
    category: MoveCategory.Attack,
    scalingStat: MoveScalingStat.STR,
    damage: 22,
    cooldown: 3,
    priority: 1,
    ppMax: 6,
    description: 'Golpe carregado — ferida (Burn).',
    effectKind: MoveEffectKind.ApplyBurn,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      burnDamagePercent: 4,
      burnTurns: 2,
    },
  }),
  skill({
    id: 'minotaur_roar',
    name: 'Rugido',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.CRIT,
    damage: 6,
    cooldown: 2,
    priority: 2,
    ppMax: 8,
    description: 'Rugido atordoante.',
    effectKind: MoveEffectKind.Confuse,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      confuseFailChance: 40,
      residualDamageFromEnemyAttackPercent: 8,
      residualTurns: 2,
    },
  }),
  skill({
    id: 'minotaur_stomp',
    name: 'Pisada',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.STR,
    damage: 12,
    cooldown: 2,
    priority: 2,
    ppMax: 8,
    description: 'Pisada esmagadora — weaken.',
    effectKind: MoveEffectKind.MovesetWeaken,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      weakenPercent: 12,
      weakenTurns: 2,
      debuffUntilBattleEnd: 0,
      battleEndDebuffWeakenPercent: 0,
    },
  }),

  // Stubs Z2/Z3 referenciados no monsterDebuffCatalog (params intermediários).
  skill({
    id: 'centipede_sting',
    name: 'Ferrão',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.CRIT,
    damage: 8,
    cooldown: 2,
    priority: 2,
    ppMax: 10,
    effectKind: MoveEffectKind.ApplyParalyze,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      paralyzeSkipTurnChance: 50,
      paralyzeTurns: 1,
      incomingBuffWeakenPercent: 12,
      incomingBuffWeakenTurns: 2,
    },
  }),
  skill({
    id: 'centipede_toxin',
    name: 'Toxina',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.CRIT,
    damage: 7,
    cooldown: 2,
    priority: 2,
    ppMax: 10,
    effectKind: MoveEffectKind.MovesetWeaken,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      weakenPercent: 12,
      weakenTurns: 2,
      debuffUntilBattleEnd: 0,
      battleEndDebuffWeakenPercent: 0,
    },
  }),
  skill({
    id: 'slime_acid',
    name: 'Ácido',
    category: MoveCategory.Attack,
    scalingStat: MoveScalingStat.STR,
    damage: 10,
    cooldown: 2,
    priority: 1,
    ppMax: 10,
    effectKind: MoveEffectKind.ApplyBurn,
    moveTarget: MoveTarget.Enemy,
    effectParams: { burnDamagePercent: 4, burnTurns: 2 },
  }),
  skill({
    id: 'slime_glue',
    name: 'Lodo',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.DEF,
    damage: 4,
    cooldown: 3,
    priority: 2,
    ppMax: 6,
    effectKind: MoveEffectKind.LockEnemyMoves,
    moveTarget: MoveTarget.Enemy,
    effectParams: { lockTurns: 1, lockMoveCount: 1 },
  }),
  skill({
    id: 'humanoid_hex',
    name: 'Hex',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.CRIT,
    damage: 8,
    cooldown: 2,
    priority: 2,
    ppMax: 10,
    effectKind: MoveEffectKind.Confuse,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      confuseFailChance: 38,
      residualDamageFromEnemyAttackPercent: 7,
      residualTurns: 2,
    },
  }),
  skill({
    id: 'humanoid_drain',
    name: 'Dreno',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.CRIT,
    damage: 8,
    cooldown: 2,
    priority: 2,
    ppMax: 10,
    effectKind: MoveEffectKind.MovesetWeaken,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      weakenPercent: 12,
      weakenTurns: 2,
      debuffUntilBattleEnd: 0,
      battleEndDebuffWeakenPercent: 0,
    },
  }),
  skill({
    id: 'golem_crush',
    name: 'Esmagar',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.STR,
    damage: 12,
    cooldown: 2,
    priority: 2,
    ppMax: 10,
    effectKind: MoveEffectKind.MovesetWeaken,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      weakenPercent: 12,
      weakenTurns: 2,
      debuffUntilBattleEnd: 0,
      battleEndDebuffWeakenPercent: 0,
    },
  }),
  skill({
    id: 'golem_quake',
    name: 'Tremor',
    category: MoveCategory.Attack,
    scalingStat: MoveScalingStat.STR,
    damage: 10,
    cooldown: 3,
    priority: 2,
    ppMax: 6,
    effectKind: MoveEffectKind.DelayedDetonation,
    moveTarget: MoveTarget.Enemy,
    effectParams: { delayedTurns: 2, delayedDamageMultiplier: 2 },
  }),
  skill({
    id: 'metal_spider_shock',
    name: 'Choque',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.CRIT,
    damage: 9,
    cooldown: 2,
    priority: 2,
    ppMax: 10,
    effectKind: MoveEffectKind.ApplyParalyze,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      paralyzeSkipTurnChance: 50,
      paralyzeTurns: 1,
      incomingBuffWeakenPercent: 12,
      incomingBuffWeakenTurns: 2,
    },
  }),
  skill({
    id: 'metal_spider_burn',
    name: 'Faísca',
    category: MoveCategory.Attack,
    scalingStat: MoveScalingStat.STR,
    damage: 11,
    cooldown: 2,
    priority: 1,
    ppMax: 10,
    effectKind: MoveEffectKind.ApplyBurn,
    moveTarget: MoveTarget.Enemy,
    effectParams: { burnDamagePercent: 4, burnTurns: 2 },
  }),
  skill({
    id: 'metal_spider_web',
    name: 'Teia de Cabo',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.DEF,
    damage: 5,
    cooldown: 3,
    priority: 2,
    ppMax: 6,
    effectKind: MoveEffectKind.LockEnemyMoves,
    moveTarget: MoveTarget.Enemy,
    effectParams: { lockTurns: 1, lockMoveCount: 1 },
  }),
  skill({
    id: 'gargoyle_gaze',
    name: 'Olhar',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.CRIT,
    damage: 6,
    cooldown: 2,
    priority: 2,
    ppMax: 10,
    effectKind: MoveEffectKind.ApplyParalyze,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      paralyzeSkipTurnChance: 50,
      paralyzeTurns: 1,
      incomingBuffWeakenPercent: 12,
      incomingBuffWeakenTurns: 2,
    },
  }),
  skill({
    id: 'gargoyle_scree',
    name: 'Grito',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.CRIT,
    damage: 8,
    cooldown: 2,
    priority: 2,
    ppMax: 10,
    effectKind: MoveEffectKind.Confuse,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      confuseFailChance: 40,
      residualDamageFromEnemyAttackPercent: 8,
      residualTurns: 2,
    },
  }),
  skill({
    id: 'gargoyle_dust',
    name: 'Poeira',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.DEF,
    damage: 7,
    cooldown: 2,
    priority: 2,
    ppMax: 10,
    effectKind: MoveEffectKind.MovesetWeaken,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      weakenPercent: 12,
      weakenTurns: 2,
      debuffUntilBattleEnd: 0,
      battleEndDebuffWeakenPercent: 0,
    },
  }),
  skill({
    id: 'scorpion_sting',
    name: 'Ferrão',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.CRIT,
    damage: 9,
    cooldown: 2,
    priority: 2,
    ppMax: 10,
    effectKind: MoveEffectKind.ApplyParalyze,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      paralyzeSkipTurnChance: 55,
      paralyzeTurns: 1,
      incomingBuffWeakenPercent: 15,
      incomingBuffWeakenTurns: 2,
    },
  }),
  skill({
    id: 'scorpion_acid',
    name: 'Ácido',
    category: MoveCategory.Attack,
    scalingStat: MoveScalingStat.STR,
    damage: 11,
    cooldown: 2,
    priority: 1,
    ppMax: 10,
    effectKind: MoveEffectKind.ApplyBurn,
    moveTarget: MoveTarget.Enemy,
    effectParams: { burnDamagePercent: 4, burnTurns: 3 },
  }),
  skill({
    id: 'scorpion_clamp',
    name: 'Pinça',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.STR,
    damage: 6,
    cooldown: 3,
    priority: 2,
    ppMax: 6,
    effectKind: MoveEffectKind.LockEnemyMoves,
    moveTarget: MoveTarget.Enemy,
    effectParams: { lockTurns: 1, lockMoveCount: 1 },
  }),
  skill({
    id: 'lizard_tongue',
    name: 'Língua',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.AGI,
    damage: 7,
    cooldown: 2,
    priority: 2,
    ppMax: 10,
    effectKind: MoveEffectKind.ApplyParalyze,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      paralyzeSkipTurnChance: 50,
      paralyzeTurns: 1,
      incomingBuffWeakenPercent: 12,
      incomingBuffWeakenTurns: 2,
    },
  }),
  skill({
    id: 'lizard_spit',
    name: 'Cuspe',
    category: MoveCategory.Attack,
    scalingStat: MoveScalingStat.STR,
    damage: 10,
    cooldown: 2,
    priority: 1,
    ppMax: 10,
    effectKind: MoveEffectKind.ApplyBurn,
    moveTarget: MoveTarget.Enemy,
    effectParams: { burnDamagePercent: 4, burnTurns: 2 },
  }),
  skill({
    id: 'lizard_daze',
    name: 'Hipnose',
    category: MoveCategory.Support,
    scalingStat: MoveScalingStat.CRIT,
    damage: 6,
    cooldown: 2,
    priority: 2,
    ppMax: 10,
    effectKind: MoveEffectKind.Confuse,
    moveTarget: MoveTarget.Enemy,
    effectParams: {
      confuseFailChance: 40,
      residualDamageFromEnemyAttackPercent: 8,
      residualTurns: 2,
    },
  }),
];

const BY_ID = new Map(MONSTER_SKILL_CATALOG.map((row) => [row.id, row]));

export function getMonsterSkillById(id: string): MonsterSkillDefinition | undefined {
  return BY_ID.get(id);
}

export function isMonsterSkillId(id: string): boolean {
  return BY_ID.has(id);
}

export function monsterSkillToSkillData(skillId: string): SkillData {
  const move = getMonsterSkillById(skillId);
  if (!move) {
    throw new Error(`[Combat] Skill de monstro desconhecida: ${skillId}`);
  }

  let skillData: SkillData = {
    id: move.id,
    name: move.name,
    damage: move.damage,
    cooldown: move.cooldown,
    basePower: move.damage,
    category: move.category,
    scalingStat: move.scalingStat,
  };

  if (move.priority !== undefined) {
    skillData = { ...skillData, priority: move.priority };
  }
  if (move.ppMax !== undefined) {
    skillData = { ...skillData, ppCurrent: move.ppMax, ppMax: move.ppMax };
  }
  if (move.moveTarget !== undefined) {
    skillData = { ...skillData, target: move.moveTarget };
  }
  if (move.effectKind !== undefined) {
    skillData = { ...skillData, effectKind: move.effectKind };
  }
  if (move.effectParams !== undefined) {
    skillData = { ...skillData, effectParams: move.effectParams };
  }

  return skillData;
}
